import json
from typing import List, Tuple, Dict, Any
from src.schemas.output_schemas import VerificationStatus, AnomalyFinding

# Note: The text in [[RAG_CONTRACT_INJECTION]] is a placeholder for where
# Person 5 (RAG Layer) would inject retrieved contract snippets.
VERIFICATION_PROMPT_TEMPLATE = """
You are the NIRIKSHAK Verification Agent (Person 4). Your role is to produce a human-readable explanation 
of the verification outcome based ONLY on the provided structured data. You are NOT responsible for 
computing numeric scores or boolean flags; you are a language generation and reasoning engine.

Here is the fused case object:
{case_json}

Here are the anomalies detected by the rule engine:
{anomalies_json}

[RAG_CONTRACT_INJECTION]
(Retrieved contract text matching the milestone will be injected here)
[/RAG_CONTRACT_INJECTION]

Instructions:
1. Compare what the contract required, what the contractor claimed, and what the evidence actually shows.
2. Make sure EVERY claim in your explanation references a specific `source_reference` or evidence field from the case object (e.g., "According to evidence.gps..."). Do not make general summaries without tracing back to the fields.
3. Conclude with a single verification_status exactly matching one of these: 
   VERIFIED, PARTIALLY_VERIFIED, DISPUTED, INSUFFICIENT_EVIDENCE.
"""

def _mock_llm_call(prompt: str, anomalies: List[AnomalyFinding]) -> Tuple[VerificationStatus, List[str]]:
    """
    Mock LLM generator. In production, this would call OpenAI/Gemini/Claude with the prompt.
    Returns a determined VerificationStatus and a generated explanation list.
    """
    explanations = []
    
    # We simulate LLM reasoning based on the presence of anomalies
    if len(anomalies) == 0:
        status = VerificationStatus.VERIFIED
        explanations.append("Based on `contract.source_reference`, the claimed progress matches the required milestones.")
        explanations.append("All `evidence` fields align perfectly with contract requirements, and no anomalies were flagged by forensics.")
    else:
        # Check for insufficient evidence
        if any("missing" in a.reason.lower() for a in anomalies):
            status = VerificationStatus.INSUFFICIENT_EVIDENCE
            explanations.append("The claim cannot be fully verified because required fields (e.g., `evidence.claim_record` or `evidence.gps`) are marked as 'missing'.")
        elif len(anomalies) > 2:
            status = VerificationStatus.DISPUTED
            explanations.append(f"Multiple discrepancies found between `contract` requirements and `evidence` data.")
            explanations.append("For example, `forensics` scores indicated potential issues with the submission integrity.")
        else:
            status = VerificationStatus.PARTIALLY_VERIFIED
            explanations.append("The claim is partially verified, but there are minor discrepancies noted in `evidence` vs `contract.quantity`.")
            
    explanations.append("Note: This explanation was generated by the reasoning engine using the fused case data.")
    return status, explanations

def generate_verification_report(case_object: Dict[str, Any], anomalies: List[AnomalyFinding]) -> Tuple[VerificationStatus, List[str]]:
    """
    Calls the LLM (mocked) to reason over the case object and anomalies, 
    producing a status and traceable explanation.
    """
    
    # Prepare the prompt
    prompt = VERIFICATION_PROMPT_TEMPLATE.format(
        case_json=json.dumps(case_object, indent=2),
        anomalies_json=json.dumps([a.model_dump() for a in anomalies], indent=2)
    )
    
    # Call the LLM
    status, explanations = _mock_llm_call(prompt, anomalies)
    
    return status, explanations
